### ISSUE TITLE
User CRUD 기능 구현

### ISSUE THREAD

**Issue by yejincode** [Kernel360/f1-Orury-Backend#27]
### 이슈 관련 도메인 (회원, 게시판, etc..)
회원(User) 도메인

### 목적
회원 기본 CRUD 구현

### 상세 내용
api 모듈 내의 회원 도메인 CRUD 구현 (DB ERD 설계 바탕)

**Comment by kkkapuq** [comment]
Assignees, projects 설정 부탁드립니다
