### ISSUE TITLE
[Bug] 대댓글 작성 시, parent_id에 대댓글을 넣어도 생성되는 문제

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/f1-Orury-Backend#84]
## 버그 내용  
```json
{
	"content" : "앙 기모띠~~~",
	"parent_id" : 3,
	"post_id" : 1
}
```
대댓글의 id를 parent_id에 넣어도 정상적으로 댓글이 생성됨.

### 버그 발생 이전 상황  
대댓글 id 3

### 정상 작동 시 기대현상
몬가 오류 처리가 되야될듯 함

**Comment by GBGreenBravo** [comment]
그렇다면, 아래의 방안이 적절할 듯 합니다! 피드백 부탁드려요~
- CommentService에 request의 parentId가 유효한 것인지(0L 이거나 해당 id를 가진 Comment의 parentId가 0L인지) 판단하는 메서드를 추가하고, 이를 Controller에서 호출.

**Comment by GBGreenBravo** [comment]
이 부분 제가 수정하겠습니다~
